trigger:
  - master

pool:
  name: 'SonarQube-Alicorp'

steps:
- script: |
    echo "Working directory: $(Build.SourcesDirectory)"
  displayName: 'Working Directory'

# Check connectivity to SonarQube
- script: |
    curl --fail --silent --show-error http://10.76.208.11:9000/api/server/version
  displayName: 'Check SonarQube Server Connectivity'
  condition: succeeded()

# Prepare SonarQube analysis configuration
- task: SonarQubePrepare@7
  inputs:
    extraProperties: |
      sonar.verbose=true
      sonar.python.version=3
      sonar.exclusions=addons/web_editor/static/src/js/**/*.js
    SonarQube: 'Sonar Alicorp'
    scannerMode: 'cli'
    configMode: 'manual'
    cliProjectKey: 'python-project-key'
    cliProjectName: 'python-code'
    cliSources: '.'
    timeoutInMinutes: 2

- task: SonarQubeAnalyze@7
  continueOnError: true

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'
